MP/ Encapsulate styles in shared styles folder
WeDevelop-ARG/cg-frontend pull request #153
Opened 2020-10-05 19:55 UTC by MPucheta

2020-10-06 12:48 UTC, Ezex360 approved these changes

2020-10-06 14:11 UTC, nahudalla requested changes

2020-10-06 14:11 UTC, nahudalla commented on src/styles/base/fonts.scss
> +.DMSansMedium {
This file is a plain `scss` file, not a module. The class names defined here will be **global**. You may want to use this file as a Sass Fragment. You only have to add an underscore at the beginning of the filename: `_fonts.scss`. Take a look at the documentation (ignore the big "heads up" section): https://sass-lang.com/documentation/at-rules/import

2020-10-06 14:11 UTC, nahudalla commented on src/styles/base/texts.scss
> +// page
Clean Code rule: If you need to add comments to separate "sections" in a file, then these "sections" probably should be in different files instead.

2020-10-06 14:11 UTC, nahudalla commented on src/styles/base/texts.scss
> +.title {
All the styles in this file should be encapsulated in different React components instead of being global CSS class names.

2020-10-07 21:05 UTC, nahudalla approved these changes

2020-10-07 21:05 UTC, merged