MP/ Refactor product detail internals and move it to Store module
WeDevelop-ARG/cg-frontend pull request #159
Opened 2020-10-13 20:30 UTC by MPucheta

2020-10-14 14:00 UTC, Ezex360 approved these changes

2020-10-15 02:47 UTC, roke77 approved these changes

2020-10-16 12:35 UTC, nahudalla requested changes

2020-10-16 12:35 UTC, nahudalla commented on src/modules/MainApp/components/Arrows/Arrow.js
> +  return ArrowRightYellow
This is returning `Black` arrow when `color === 'yellow'` and vice versa, is this intended?

2020-10-16 12:35 UTC, nahudalla commented on src/modules/MainApp/components/Slider/index.js
> +import DotUnselected from './DotUnselected'
Are you sure we want two components that do exactly the same, look exactly the same, but only change a minor style? Why not have a `Dot` component and receive a `selected` boolean prop to change the styling?

2020-10-16 12:35 UTC, nahudalla commented on src/modules/MainApp/components/Slider/DotSelected.js
> +    <button type='button' className={classes.dotSelected} />
If this button behaves as a kind of "selector" (a slider, checkbox, radio or similar), consider adding the `aria-selected` property to improve usability.

2020-10-16 12:35 UTC, nahudalla commented on src/modules/Store/pages/ProductDetail/Costs/index.js
> +        <img src={ShippingIcon} alt='shipping-icon' />
`alt` text is human-readable. It should be something like `Shipping icon`. Also, if it's not meaningful content for the user it's best to leave the `alt` prop set as an empty string `alt=''`.

2020-10-19 14:31 UTC, nahudalla approved these changes

2020-10-19 14:31 UTC, nahudalla commented on src/modules/MainApp/components/Slider/Dot.js
> +  className: PropTypes.oneOfType([PropTypes.string, PropTypes.array])
Are you sure React accepts arrays as the `className` prop or an element?

2020-10-19 14:31 UTC, nahudalla commented on src/modules/MainApp/components/Slider/index.js
> +  }
:thinking: is this really necessary? Why not do it directly in the `map` below? Maybe something like this is better?
```javascript
<Dot
  key={`dot-${index}`}
  className={classnames({
    [classes.dotSelected]: index === currentIndex,
    [classes.dotUnselected]: index !== currentIndex
  })}
/>
```

2020-10-19 15:48 UTC, merged