Eg/refactor end checkout
WeDevelop-ARG/cg-frontend pull request #160
Opened 2020-10-14 17:37 UTC by Ezex360

Needs https://github.com/WeDevelop-ARG/cg-frontend/pull/159.

2020-10-16 12:45 UTC, nahudalla requested changes

2020-10-16 12:45 UTC, nahudalla commented on src/modules/Store/pages/Checkout/PurchaseSuccess/ProductShare/index.js
> +        <p className={classes.productUrl}>http://comprasgrupales.com/{(productName).replace(/ /g, '-').toLowerCase()}</p>
:thinking: I'd maybe use an environment variable to configure the website's base URL. Also, **always** use HTTPS.

2020-10-16 12:47 UTC, nahudalla commented on src/modules/Store/pages/Checkout/PurchaseSuccess/ProductShare/index.js
> +        <p className={classes.productUrl}>http://comprasgrupales.com/{(productName).replace(/ /g, '-').toLowerCase()}</p>
You can configure environment variables like this one in the `cloudbuild_xxx.yaml` files in the root of the repo.

2020-10-19 14:34 UTC, nahudalla approved these changes

2020-10-19 17:44 UTC, MPucheta reviewed
This is a "self-review", I will change them right away

2020-10-19 17:44 UTC, MPucheta commented on src/modules/Store/pages/Checkout/PurchaseSuccess/ProductInfo/index.js
> +        <ImageAsBackround imageUrl={product.photos[0].url} className={classes.image} />
Typo `backround`

2020-10-19 17:44 UTC, MPucheta commented on src/modules/Store/pages/Checkout/PurchaseSuccess/ProductInfo/styles.module.scss
> +  border-top: 1px solid #F1F3F3;
Put color variables

2020-10-19 17:44 UTC, MPucheta commented on src/modules/Store/pages/Checkout/PurchaseSuccess/ProductShare/styles.module.scss
> +  background: #FFFFFF;
Use colors

2020-10-19 17:44 UTC, MPucheta commented on src/modules/Store/pages/Checkout/PurchaseSuccess/index.js
> +        &#60;  Volver a la pagina principal
typo `página`, unnecesssary lambda `()=> goToHome()`

2020-10-19 17:44 UTC, MPucheta commented on src/modules/Store/pages/Checkout/PurchaseSuccess/index.js
> +import GroupProgress from '~/src/components/GroupProgress'
Replace with the GroupProgress inside `MainApp`

2020-10-19 17:44 UTC, MPucheta commented on src/modules/Store/pages/Checkout/PurchaseSuccess/index.js
> +          <p>Compartí y suma gente para acceder más rápido a tu producto</p>
`sumá`

2020-10-19 17:44 UTC, MPucheta commented on src/modules/Store/pages/Checkout/PurchaseSuccess/styles.module.scss
> +  background: #FFFFFF;
Use color variables

2020-10-19 20:05 UTC, merged