Add photos urls instead of photo file only
WeDevelop-ARG/cg-frontend pull request #161
Opened 2020-10-15 14:46 UTC by Ezex360

Added textarea for now, so users can paste their photos urls and use those to be shown in the product gallery.

2020-10-15 15:59 UTC, roke77 approved these changes

2020-10-16 12:50 UTC, nahudalla requested changes

2020-10-16 12:50 UTC, nahudalla commented on src/modules/SellerProducts/components/ProductForm/index.js
> +            <label className={classes.label}>o ingresa las URL de tus imagenes separadas por comas</label>
No sería más fácil separarlas por saltos de línea para el usuario? Las comas son caracteres válidos en las URLs y además son difíciles de distinguir dónde termina una y otra para URLs largas...

2020-10-16 12:53 UTC, Ezex360 commented on src/modules/SellerProducts/components/ProductForm/index.js
> +            <label className={classes.label}>o ingresa las URL de tus imagenes separadas por comas</label>
Es una solucion temporal hasta que se cree el diseño de como añadir las URLs, pero si las URLs pueden tener comas entonces ahi lo cambio

2020-10-19 14:36 UTC, nahudalla approved these changes

2020-10-19 14:36 UTC, merged