MP/ Split customer/seller signup forms with new routes
WeDevelop-ARG/cg-frontend pull request #162
Opened 2020-10-15 21:05 UTC by MPucheta

There is some "sharing" that can be abstracted, but I really feel like "Customer" and "Seller" are two different actors that will evolve differently, hence they shouldn't share things.

2020-10-15 21:14 UTC, roke77 approved these changes

2020-10-16 12:34 UTC, Ezex360 approved these changes

2020-10-16 13:08 UTC, nahudalla requested changes

2020-10-16 13:08 UTC, nahudalla commented on src/modules/Auth/components/SignUpSellerForm/styles.module.scss
> +  grid-template-columns: repeat(2,1fr);
```suggestion
  grid-template-columns: repeat(2, 1fr);
```

2020-10-16 13:08 UTC, nahudalla commented on src/modules/Auth/components/SignUpSellerForm/styles.module.scss
> +  color:$black;
```suggestion
  color: $black;
```

2020-10-16 13:08 UTC, nahudalla commented on src/modules/Auth/components/SignUpSellerForm/styles.module.scss
> +  color:$black;
```suggestion
  color: $black;
```

2020-10-16 13:08 UTC, nahudalla commented on src/modules/Auth/pages/SignUpCustomer/index.js
> +    await logFormSubmit('customer_signup_form')
**Caution!** This isn't just another name to change lightly. This is used in Google Analytics. Maybe we need to think about it more thoroughly.

2020-10-16 13:08 UTC, nahudalla commented on src/modules/MainApp/components/Select/index.js
> +const Select = ({ className, children, ...props }) => {
This Select is not correctly implemented... Maybe it was an old implementation, buy we should consider using a library such as `react-select` for these cases. The main problem is accessibility. For example, the _focus_ of an element is not just a visual matter, it's a functional one. I see that we're applying "focus" styles conditionally, but the input is never really focused by the browser.

2020-10-23 14:35 UTC, nahudalla requested changes

2020-10-23 14:35 UTC, nahudalla commented on src/modules/MainApp/components/Select/styles.module.scss
> +:global .react-select__control {
Don't use global CSS classes. You can apply it specifically for this component with the following selector:
```scss
.selectContainer {
  [class^='react-select__control'] {
    // ... your styles
  }
}
```

2020-10-23 14:35 UTC, nahudalla commented on src/modules/MainApp/components/Select/styles.module.scss
> +:global .react-select__value-container {
Same here.

2020-10-26 13:01 UTC, nahudalla approved these changes

2020-10-26 13:02 UTC, merged